### ISSUE TITLE
Manage Creator Order using list order

### ISSUE THREAD

**Issue by horsburgh** [sblack-usu/hs_rdf#2]
The order of creators in a resource matters. HydroShare has a creator order attribute for a creator that determines the order in which creators are displayed on the resource landing page. We should hide the creator order property of the Creator object and just manage creator order according to the order of Creator objects in the list of Creators.

**Comment by sblack-usu** [comment]
done.  https://github.com/sblack-usu/hs_rdf/blob/master/tests/functional_tests.py#L33
