### ISSUE TITLE
Downloading an aggregation fails

### ISSUE THREAD

**Issue by horsburgh** [sblack-usu/hs_rdf#3]
I create a single file aggregation and save it successfully. I then try to download it without specifying a download path. I get the following error. The other download functions do not require a download path, so I'm not sure why downloading an aggregation would require one.

![image](https://user-images.githubusercontent.com/3485902/102701856-cd8ab500-4218-11eb-9e43-3f12fcbf6eca.png)

If I specify a download path, I get the following error. I get this same error if I try to remove or delete the aggregation.

![image](https://user-images.githubusercontent.com/3485902/102701902-38d48700-4219-11eb-98c4-eef0ec2560b3.png)

**Comment by sblack-usu** [comment]
Aggregation download was missing the default save_path.  I'll get this patched soon.

**Comment by sblack-usu** [comment]
fixed. https://github.com/sblack-usu/hs_rdf/blob/master/hs_rdf/implementations/hydroshare.py#L320
